owner: ddrayko
repo: status

sites:
  - name: Portfolio
    url: https://drayko.xyz
  - name: FlexURL
    url: https://flexurl.link
  - name: ToolsBoxMachine (TBXM)
    url: https://tbxm.drayko.xyz
  - name: ZeroHost
    url: https://zero-host.org

status-website:
  cname: status.drayko.xyz
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
