owner: ddrayko
repo: status

sites:
  - name: Portfolio
    url: https://drayko.xyz
    icon: https://img.drayko.xyz/ddrayko.png
  - name: FlexURL
    url: https://flexurl.link
    icon: https://img.drayko.xyz/flexurl-logo.png
  - name: ToolsBoxMachine (TBXM)
    url: https://tbxm.drayko.xyz
    icon: https://img.drayko.xyz/tbxm-logo.png
  - name: ZeroHost
    url: https://zero-host.org
    expectedStatusCodes:
      - 403
    icon: https://img.drayko.xyz/zerohost-logo.png
  - name: DraykoSearch
    url: https://search.drayko.xyz

status-website:
  cname: status.drayko.xyz
  logoUrl: https://img.drayko.xyz/ddrayko.svg
  name: Upptime
  favicon: https://img.drayko.xyz/ddrayko.png
  faviconSvg: https://img.drayko.xyz/ddrayko.svg

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
